[package]
name = "SpaceEngine"
version = "0.1.0"
authors = ["Sam Gosden <s.j.gosden2@newcastle.ac.uk>"]
edition = "2024"

[features]

[dependencies]

pixels = "0.14.0"
winit =  { version = "0.29" , features = ["rwh_05"] }
ultraviolet = {version ="0.9.2", features = ["f64"]}
